piro20_Ajax_Pirostagram/comments/urls.py
from django.urls import path
from .views import *

app_name = 'comments'

urlpatterns = [
    path('create/<int:pk>', comment_create, name='comment_create'),
]

piro20_Ajax_Pirostagram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('posts.urls')),
    path("comments/", include('comments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

piro20_Ajax_Pirostagram/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('like_ajax/', like_ajax, name='like_ajax'),
    path('delete_ajax/<int:pk>/', delete_ajax, name='delete_ajax'),
    path('create_ajax/<int:pk>/', create_ajax, name='create_ajax'),
    path('search/', search_view, name='search_view'),
]

piro20_Ajax_Pirostagram/comments/models.py
from django.db import models
from posts.models import Post 
# Create your models here.
class Comment(models.Model):
    content = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)

piro20_Ajax_Pirostagram/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=24)
    content = models.TextField()
    like = models.BooleanField()

piro20_Ajax_Pirostagram/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

piro20_Ajax_Pirostagram/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

piro20_Ajax_Pirostagram/comments/views.py
from django.shortcuts import render, redirect
from .forms import CommentForm
# Create your views here.
def comment_create(request, pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', pk=pk)
        else:
            ctx = {
                'form': form,
            }
            return render(request, 'comments/comments_create.html', ctx)
    else:
        form = CommentForm()
        ctx = {
                'form': form,
        }
        return render(request, 'comments/comments_create.html', ctx)

piro20_Ajax_Pirostagram/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from comments.models import Comment
from comments.forms import CommentForm
from django.db.models import Q

# Create your views here.
def main(request):
    #모든 게시물 가져오기
    posts = Post.objects.all()
    search_query = request.GET.get('q', '')
    if search_query:
        posts = Post.objects.filter(Q(title__icontains=search_query))
    # 각 게시물에 대한 연관된 코멘트 가져오기
    post_comments = {}
    for post in posts:
        comments = Comment.objects.filter(post=post)
        post_comments[post.id] = comments
    
    #print("여기", post_comments) 
    ctx = {
        'posts': posts,
        #검색 결과가 없는 경우를 위해 추가
        #'comments': comments,
        'comments': post_comments.get(post.id, []) if posts else [],
        'search_query': search_query,
    }
    return render(request, 'posts/posts_list.html', ctx)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:main')
        else:
            ctx = {
                'form': form,
            }
            return render(request, 'posts/post_create.html', ctx)
    else:
        form = PostForm()
        ctx = {
                'form': form,
        }
        return render(request, 'posts/post_create.html', ctx)

def detail(request, pk):
    post = Post.objects.get(id=pk)
    form = CommentForm()
    ctx ={
        'post': post,
        'comments': post.comment_set.all(),
        'form': form
    }
    return render(request, 'posts/post_detail.html', ctx)

# def comment_create(request, pk):
#     post = Post.objects.get(pk=pk)
#     comment_form = CommentForm(request.POST)
#     if comment_form.is_valid():
#         comment = comment_form.save(commit=False)
#         comment.post = post
#         comment.save()
#     return redirect('posts:detail', post.pk)

import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def like_ajax(request):
    req = json.loads(request.body)
    post_id = req['id']

    post = Post.objects.get(id=post_id)

    post.like = not post.like
    
    post.save()

    return JsonResponse({'id': post_id, 'liked': post.like})

@csrf_exempt
def delete_ajax(request, pk):
    if request.method == 'POST':
        comment = Comment.objects.get(id=pk)
        comment_id = comment.id
        comment.delete()
        return JsonResponse({'id': comment_id})
    
@csrf_exempt
def create_ajax(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(id=pk)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()

            # 새로운 댓글 데이터를 응답으로 반환
            response_data = {
                'id': comment.id,
                'content': comment.content,
            }

            return JsonResponse(response_data)

    return JsonResponse({'error': '유효하지 않은 폼 데이터'})

def search_view(request):
    search_query = request.GET.get('q', '')
    results = Post.objects.filter(Q(title__icontains=search_query))

    response_data = {
        'results': [{'id': post.id, 'title': post.title} for post in results]
    }
    return JsonResponse(response_data)

piro20_Ajax_Pirostagram/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&display=swap" rel="stylesheet">
    <title>Pirostagramming</title>
  </head>
  <body>
    <header>
      <a href="{% url 'posts:main' %}" id="main_title">Pirostagramming</a>
      <a href="{% url 'posts:create' %}" id="create_post">글 생성</a>
    </header>

    {% block content %} {% endblock %}
    <script src="https://kit.fontawesome.com/880ce38071.js" crossorigin="anonymous"></script>
  </body>
</html>

piro20_Ajax_Pirostagram/templates/comments/comments_create.html
{% extends 'base.html' %} 
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="submit">
    </form>
{% endblock %}

piro20_Ajax_Pirostagram/templates/posts/post_create.html
{% extends 'base.html' %} 
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="submit">
    </form>
{% endblock %}

piro20_Ajax_Pirostagram/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<div class="detail_container">
    <div class="detail_lr">
        <div class="detail_title">{{post.title}}</div>
        <div>{{post.content}}</div>
        <form id="commentForm" action="" method="POST" onsubmit="return onClickCreateComment({{post.id}});"">
            {% csrf_token %}
            <div class="comment_create_form">
                <div>{{ form.as_table }}</div>
                <div class="submit_btn" onclick="onClickCreateComment({{post.id}})">작성하기</div>
            </div>
            <!-- <input type="submit" value="submit"> -->
        </form>
        <ul id="commentsContainer" class="comments-container">
            <p>댓글창</p>
            {% for comment in comments %}
                <li class="comment_ins comment-id-{{comment.id}}">
                    <div class="comment_title">댓글 : {{comment.content}}</div>
                    <div class="delete_btn" onclick="onClickDelete({{comment.id}})">삭제하기</div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<script>
    // onClickDelete 함수 업데이트
    const onClickDelete = (id) => {
        const requestDelete = new XMLHttpRequest();
        const url = `/delete_ajax/${id}/`; 
        requestDelete.open("POST", url, true);
        requestDelete.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        requestDelete.send();

        // 응답을 처리
        requestDelete.onreadystatechange = () => {
            if (requestDelete.readyState === XMLHttpRequest.DONE) {
                //console.log(requestDelete.response); 

                if (requestDelete.status < 400) {
                    const { id } = JSON.parse(requestDelete.response);

                    //console.log(id)
                    const commentContainer = document.querySelector(`.comment-id-${id}`);
                    //console.log(id)
                    //console.log(document.querySelector(`.comment-id-${id}`));
                    //console.log(commentContainer);

                    if (commentContainer) {
                        commentContainer.remove();
                    }
                }
            }
        };
    };

    const onClickCreateComment = (id) => {
        const requestCreate = new XMLHttpRequest();
        const url = `/create_ajax/${id}/`;
        
        requestCreate.open("POST", url, true);
        requestCreate.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    
        // FormData: 폼을 받아서 서버로 전송하기 위함
        const formData = new FormData(document.getElementById('commentForm'));
    
        requestCreate.onreadystatechange = function () {
            if (requestCreate.readyState === XMLHttpRequest.DONE) {
                if (requestCreate.status < 400) {
                    const { id, content } = JSON.parse(requestCreate.response);
    
                    // comment를 추가하기 위해 받아옴
                    const commentContainer = document.getElementById('commentsContainer');
    
                    // 새 댓글 html 만들기
                    const newComment = document.createElement('li');
                    newComment.className = `comment_ins comment-id-${id}`;
                    newComment.innerHTML = `<div class="comment_title">댓글 : ${content}</div>
                                            <div class="delete_btn" onclick="onClickDelete(${id})">삭제하기</div>`;
    
                    // 추가하기
                    commentContainer.appendChild(newComment);
                    // 작성 후 폼 지우기
                    document.getElementById('commentForm').reset();
                }
            }
        };
    
        // URLSearchParams로 formData를 URL-encoded 문자열로 변환
        // URLSearchParams 삭제하면 댓글 내용이 아닌 undefined가 출력
        requestCreate.send(new URLSearchParams(formData));
    };
</script>
{% endblock content %}

piro20_Ajax_Pirostagram/templates/posts/posts_list.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<div class="search-container">
    <form action="{% url 'posts:main' %}" method="get">
        <input type="text" name="q" value="{{ search_query }}" class="search-text" id="searchInput" oninput="performSearch()" placeholder="검색어 입력">
        <input type="submit" class="search-btn" value="검색">
    </form>
    <ul id="searchResults"></ul>
</div>
<div id="container">
    {% for post in posts %}
        <div class="post_container post-id-{{ post.id }}">
            <a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
            <div>{{ post.content }}</div>
            <div class="like_btn" onclick="onClickLike({{post.id}})">
                {% if post.like %}
                    <i class="fa-solid fa-heart" style="color:red"></i>
                {% else %}
                    <i class="fa-regular fa-heart"></i>
                {% endif %}
            </div>

            <a href="{% url 'posts:detail' post.id %}">댓글 쓰러 가기</a>
        </div>
    {% endfor %}
</div>
<script>
    // 서버에서 id와 like 여부를 계산하여 응답하면 그 값으로 처리
    const onClickLike = (id) => {
        const requestLike = new XMLHttpRequest();
        const url = "/like_ajax/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        requestLike.send(JSON.stringify({ id: id }));
    
        //상태가 바뀔 때마다 호출
        requestLike.onreadystatechange = () => {
            if (requestLike.readyState === XMLHttpRequest.DONE) {
                if (requestLike.status < 400) {
                    const { id, liked } = JSON.parse(requestLike.response);
                    const element = document.querySelector(`.post-id-${id} .like_btn i`);
                    //console.log(element);
                    //화면에 출력
                    if (liked) {
                        element.classList.remove("fa-regular");
                        element.classList.add("fa-solid");
                        element.style.color = "red";
                    } else {
                        element.classList.remove("fa-solid");
                        element.classList.add("fa-regular");
                    }
                    //console.log(liked);
                }
            }
        };
    }


    function performSearch() {
        const searchInput = document.getElementById('searchInput').value;

        // AJAX 요청
        const xhr = new XMLHttpRequest();
        const url = `/search/?q=${encodeURIComponent(searchInput)}`;
        
        xhr.open('GET', url, true);
        xhr.onreadystatechange = function () {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                if (xhr.status === 200) {
                    const resultsContainer = document.getElementById('searchResults');
                    const response = JSON.parse(xhr.responseText);

                    // 검색 결과를 동적으로 업데이트
                    resultsContainer.innerHTML = '';
                    for (const result of response.results) {
                        const listItem = document.createElement('li');
                        listItem.textContent = result.title;
                        resultsContainer.appendChild(listItem);
                    }
                }
            }
        };
        
        xhr.send();
    }
</script>
{% endblock %}