SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('ideas.urls')),
    path('toolss/', include('toolss.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
    path('', main, name='main'),
    path('detail/<int:pk>', detail, name='detail'),
    path('create/', create, name='create'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
    path('star_list/<int:pk>',star_list,name='star_list'),
    path('star_detail/<int:pk>',star_detail,name='star_detail'),
    path('update_interested_num/', update_interested_num, name='update_interested_num'),
    
]

SWIDEA_SITE/toolss/urls.py
from django.urls import path
from .views import *

app_name = 'toolss'

urlpatterns = [
    path('', main, name='main'),
    path('detail/<int:pk>', detail, name='detail'),
    path('create/', create, name='create'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
]

SWIDEA_SITE/ideas/models.py
from django.db import models
from toolss.models import Tool

# Create your models here.
class Idea(models.Model):
    title = models.CharField('제목', max_length=24)
    photo = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')
    content = models.CharField('아이디어 설명', max_length=100)
    interestedNum = models.IntegerField('아이디어 관심도', default=0)

    def get_tool_choices():
        toolss = Tool.objects.all()
        return [(tool.name, tool.name) for tool in toolss]

    tool = models.CharField('예상 개발툴', max_length=24, choices=get_tool_choices())
    
    created_date = models.DateTimeField('작성일', auto_created=True, auto_now_add=True)
    updated_date = models.DateTimeField('수정일', auto_created=True, auto_now=True)

    star = models.BooleanField(default = False)

SWIDEA_SITE/toolss/models.py
from django.db import models

# Create your models here.
class Tool(models.Model):
    name = models.CharField('이름', max_length=24)
    kind = models.CharField('종류', max_length=24)
    explain = models.TextField('개발툴 설명')

SWIDEA_SITE/ideas/forms.py
from django import forms
from .models import Idea

class IdeaForm(forms.ModelForm):
    class Meta():
        model = Idea
        fields = ('__all__')

SWIDEA_SITE/toolss/forms.py
from django import forms
from .models import Tool

class ToolForm(forms.ModelForm):
    class Meta():
        model = Tool
        fields = ('__all__')

SWIDEA_SITE/ideas/views.py
from django.shortcuts import render, redirect
from .models import Idea
from .forms import IdeaForm
from django.http import JsonResponse
from django.views.decorators.http import require_POST
 
def main(request):
    # sort_select = request.GET.get('sort_select')
    ideas = Idea.objects.all()
    search_mode = request.GET.get('search_mode')
    if search_mode == '찜하기순':
        ideas = ideas.order_by('-interestedNum')
    elif search_mode == '이름순':
        ideas = ideas.order_by('title')
    elif search_mode == '등록순':
        ideas = ideas.order_by('created_date')
    elif search_mode == '최신순':
        ideas = ideas.order_by('-created_date')
    ctx = {'ideas': ideas}
    return render(request, 'ideas/idea_list.html', ctx)

def detail(request, pk):
    idea = Idea.objects.get(id=pk)
    ctx ={'idea':idea}
    return render(request, 'ideas/idea_detail.html', ctx)

def create(request):
    if request.method =='GET':
        form = IdeaForm()
        ctx ={'form': form}
        return render(request, 'ideas/idea_create.html', ctx)
    #POST일때
    form = IdeaForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
    return redirect('ideas:main')

def delete(request,pk):
    if request.method == "POST":
        Idea.objects.get(id=pk).delete()
    return redirect('ideas:main')

def update(request,pk):
    idea = Idea.objects.get(id=pk)
    if request.method == "GET":
        form = IdeaForm(instance=idea) #instance는 입력되어있는 값을 넣기 위해서
        ctx = {'form': form, 'pk': pk}
        return render(request, 'ideas/idea_update.html', ctx)
    form = IdeaForm(request.POST, request.FILES, instance=idea)
    if form.is_valid():
        form.save()
    return redirect('ideas:detail', pk)

def star_list(request,pk):
  star_toggle = Idea.objects.get(id=pk)
  if star_toggle.star:
    star_toggle.star = False
  else:
    star_toggle.star = True
  star_toggle.save()
  return redirect('ideas:main')

def star_detail(request,pk):
  star_toggle = Idea.objects.get(id=pk)
  if star_toggle.star:
    star_toggle.star = False
  else:
    star_toggle.star = True
  star_toggle.save()
  return redirect('ideas:detail',pk)

@require_POST
def update_interested_num(request):
    idea_id = request.POST.get('idea_id')
    increment = int(request.POST.get('increment'))

    try:
        idea = Idea.objects.get(pk=idea_id)
        idea.interestedNum += increment
        idea.save()
        return JsonResponse({'interestedNum': idea.interestedNum})
    except Idea.DoesNotExist:
        return JsonResponse({'error': '아이디어를 찾을 수 없습니다.'})

SWIDEA_SITE/toolss/views.py
from django.shortcuts import render, redirect
from .models import Tool
from .forms import ToolForm
# Create your views here.
def main(request):
    tools = Tool.objects.all()
    ctx = {'tools':tools}
    return render(request, 'toolss/tool_list.html', ctx)

def detail(request, pk):
    tool = Tool.objects.get(id=pk)
    ctx ={'tool':tool}
    return render(request, 'toolss/tool_detail.html', ctx)

def create(request):
    if request.method == 'GET':
        form = ToolForm()
        ctx = {'form': form}
        return render(request, 'toolss/tool_create.html', ctx)

    form = ToolForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('toolss:main')

def delete(request, pk):
    if request.method == "POST":
        Tool.objects.get(id=pk).delete()
    return redirect('toolss:main')

def update(request, pk):
    tool = Tool.objects.get(id=pk)
    if request.method == 'GET':
        form = ToolForm(instance=tool)
        ctx = {'form': form, 'pk': pk}
        return render(request, 'toolss/tool_update.html', ctx)
    
    form = ToolForm(request.POST, instance=tool)
    if form.is_valid():
        form.save()
    return redirect('toolss:main')

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css"
    />
    {% block head %} {% endblock %}
  </head>
  <body>
    <nav>
      <div id="nav-left">
        <a href="/" id="logo"><h1>My SW Ideas</h1> </a>
      </div>
      <div id="nav-right">
        <a href="{% url 'ideas:create' %}">아이디어 등록</a>
        <a href="{% url 'ideas:main' %}">아이디어 관리</a>
        <a href="{% url 'toolss:create' %}">개발도구 등록</a>
        <a href="{% url 'toolss:main' %}">개발도구 관리</a>
      </div>
    </nav>
    <hr />
    {% block content %} {% endblock %}
  </body>
  <script>
    document.querySelectorAll(".star-icon").forEach(function (element) {
      element.addEventListener("click", function () {
        var fillStar = this.querySelector(".fill");
      });
    });
  </script>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

  <script>
    $(document).ready(function () {
      $(".interestedNum button").on("click", function (event) {
        event.preventDefault();
        event.stopPropagation();

        var button = $(this);
        var ideaId = button.closest(".item").data("idea-id");
        var increment = button.text() === "+" ? 1 : -1;

        var interestCountElement = button
          .closest(".item")
          .find(".interestedNum");

        // 버튼을 일시적으로 비활성화
        button.prop("disabled", true);

        $.ajax({
          type: "POST",
          url: "{% url 'ideas:update_interested_num' %}",
          data: {
            idea_id: ideaId,
            increment: increment,
            csrfmiddlewaretoken: "{{ csrf_token }}",
          },
          success: function (data) {
            var newInterestedNum = data.interestedNum;
            interestCountElement.text(newInterestedNum);
          },
          error: function (error) {
            console.log("에러 발생: ", error);
          },
          complete: function () {
            // 비동기 요청이 완료된 후 버튼을 다시 활성화
            button.prop("disabled", false);
          },
        });
      });
    });
  </script>
</html>

SWIDEA_SITE/templates/ideas/idea_create.html
{% extends 'base.html' %} {%block head%}
<title>idea_create</title>
{% endblock %} {%block content%}
<div class="content-wrapper">
  <form
    action="{% url 'ideas:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <div class="btn-wrapping">
      <button class="btn btn-success">등록</button>
    </div>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="content-detail">
  {% if idea.photo.url != '' %}
  <div class="image-container">
    <img src="{{idea.photo.url}} " alt="아이디어 이미지" class="img-detail" />
  </div>
  {% else %}
  <div class="image-container">
    <img
      src="{% static 'image/no_img.png' %}"
      alt="대체 이미지"
      class="img-detail"
    />
  </div>
  {% endif %}

  <div class="content-detail-1">
    {% if idea.star %}
    <p class="title-detail">
      {{idea.title}}
      <a
        class="star-icon star-detail"
        href="{% url 'ideas:star_detail' idea.pk %}"
      >
        <i class="fa-solid fa-star fill check" style="color: yellow"></i>
      </a>
    </p>
    {% else %}
    <p class="title-detail">
      {{idea.title}}
      <a
        class="star-icon star-detail"
        href="{% url 'ideas:star_detail' idea.pk %}"
      >
        <i class="fa-regular fa-star outline"></i>
      </a>
    </p>
    {% endif %}
    <p>아이디어 관심도: {{idea.interestedNum}}</p>
    <p>예상 개발 툴: {{idea.tool}}</p>
    <p>아이디어 설명: {{idea.content}}</p>
    <hr />

    <div class="btn-wrapping">
      <form action="{% url 'ideas:delete' idea.pk %}" method="POST">
        {%csrf_token%}
        <button type="submit" class="btn btn-danger">삭제</button>
        <a href="{% url 'ideas:main'%}" class="btn btn-primary">목록</a>
        <a href="{% url 'ideas:update' idea.pk %}" class="btn btn-success"
          >수정</a
        >
      </form>
    </div>
  </div>
</div>
{% endblock content %}

SWIDEA_SITE/templates/ideas/idea_list.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>아이디어 목록</title>
{%endblock%} {%block content%}
<form action="{% url 'ideas:main' %}" method="get" id="search_mode">
  <div class="container-sort">
    <select name="search_mode" onchange="submit()">
      <option value="" selected>정렬기준</option>
      <option value="찜하기순">찜하기순</option>
      <option value="이름순">이름순</option>
      <option value="등록순">등록순</option>
      <option value="최신순">최신순</option>
    </select>
  </div>
</form>
<div class="content-wrapper">
  <!-- 글 목록 -->
  {% for idea in ideas %}
  <div class="item" data-idea-id="{{ idea.id }}">
    {% if idea.photo.url != null and idea.photo.url != '' %} {% if idea.star %}
    <div class="image-container">
      <img src="{{ idea.photo.url }}" alt="" class="img" />
      <a class="star-icon star-move" href="{% url 'ideas:star_list' idea.pk %}">
        <i
          class="fa-solid fa-star fill check over-icon"
          style="color: yellow"
        ></i>
      </a>
    </div>
    {% else %}
    <div class="image-container">
      <img src="{{ idea.photo.url }}" alt="" class="img" />
      <a class="star-icon star-move" href="{% url 'ideas:star_list' idea.pk %}">
        <i class="fa-regular fa-star outline over-icon"></i>
      </a>
    </div>
    {% endif %} {% else %} {% if idea.star %}
    <div class="image-container">
      <img src="{% static 'image/no_img.png' %}" alt="대체텍스트" class="img" />
      <a class="star-icon star-move" href="{% url 'ideas:star_list' idea.pk %}">
        <i
          class="fa-solid fa-star fill check over-icon"
          style="color: yellow"
        ></i>
      </a>
    </div>
    {% else %}
    <div class="image-container">
      <img src="{% static 'image/no_img.png' %}" alt="대체텍스트" class="img" />
      <a class="star-icon star-move" href="{% url 'ideas:star_list' idea.pk %}">
        <i class="fa-regular fa-star outline"></i>
      </a>
    </div>
    {% endif %} {% endif %}
    <div class="info">
      <a href="{% url 'ideas:detail' idea.pk %}" class="title">
        {{ idea.title }}
      </a>
      <p class="tool">예상 개발 툴: {{idea.tool}}</p>
      <p class="interestedNum">
        아이디어 관심도:
        <button>-</button>
        {{ idea.interestedNum }}
        <button>+</button>
      </p>
    </div>
  </div>
  {% endfor %}
</div>
<script>
  function submitForm() {
    document.getElementById("search_mode").submit();
  }
</script>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_update.html
{% extends 'base.html' %} {%block head %}
<title>idea_detail</title>
{%endblock%} {%block content%}
<div class="content-wrapper">
  <form
    action="{% url 'ideas:update' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <div class="btn-wrapping">
      <button class="btn btn-success">수정</button>
    </div>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/templates/toolss/tool_create.html
{% extends 'base.html' %} {%block head%}
<title>tool_create</title>
{% endblock %} {%block content%}
<div class="content-wrapper">
  <form action="{% url 'toolss:create' %}" method="post">
    {%csrf_token%} {{form.as_p}}
    <div class="btn-wrapping">
      <button class="btn btn-success">추가</button>
    </div>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/templates/toolss/tool_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="content-detail-tool">
  <p class="title-detail">{{tool.name}}</p>
  <p>{{tool.kind}}</p>
  <p>{{tool.explain}}</p>
  <div class="btn-wrapping">
    <form action="{% url 'toolss:delete' tool.pk %}" method="POST">
      {%csrf_token%}
      <button type="submit" class="btn btn-danger">삭제</button>
      <a href="{% url 'toolss:main'%}" class="btn btn-primary">목록</a>
      <a href="{% url 'toolss:update' tool.pk %}" class="btn btn-success"
        >수정</a
      >
    </form>
  </div>
</div>
{% endblock content %}

SWIDEA_SITE/templates/toolss/tool_list.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>개발툴 목록</title>
{%endblock%} {%block content%}
<div class="content-wrapper">
  <!-- 글 목록 -->
  {% for tool in tools %}
  <div class="item">
    <div class="info">
      <a href="{% url 'toolss:detail' tool.pk %}" class="title">
        {{ tool.name }}
      </a>
      <p class="kind">{{tool.kind}}</p>
      <p class="explain">{{tool.explain}}</p>
    </div>
  </div>
  {% endfor %}
</div>
{%endblock%}

SWIDEA_SITE/templates/toolss/tool_update.html
{% extends 'base.html' %} {%block head %}
<title>tool_detail</title>
{%endblock%} {%block content%}
<div class="content-wrapper">
  <form action="{% url 'toolss:update' pk %}" method="post">
    {%csrf_token%} {{form.as_p}}
    <div class="btn-wrapping">
      <button class="btn btn-success">수정</button>
    </div>
  </form>
</div>
{%endblock%}